### ISSUE TITLE
Update free packages

### ISSUE THREAD

**Issue by shakeyourbunny** [5x/easy-steam-free-packages#1]
**Is your feature request related to a problem? Please describe.**
Not all free packages in table.

**Describe the solution you'd like**
Can you update the free license tables to have the newest free stuff in it?

**Describe alternatives you've considered**

Alternative solution would be to describe how to extracted all free new licenses to manually add them.

**Comment by 5x** [comment]
c31a438f0e8b004780f77a05d9ef32d516ea6c1c, Updated free packages db. Now contains over 10,000 ids.
