### ISSUE TITLE
I don't see the games in my library

### ISSUE THREAD

**Issue by 002-sans** [5x/easy-steam-free-packages#24]
**Describe the bug**
I started that but I don't see the games in my library (after 10m)

**Comment by 002-sans** [comment]
is it normal ?

**Comment by dafunks** [comment]
after 10mins you will barely have go any. Maybe it activated DLCs or software. This script runs for days... weeks. Sadly Steam limits how many games can be activated so it can be very very close. I believe it gives you how long in mins so check it.
